# Generated by Django 2.0 on 2020-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(upload_to='dp/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40)),
                ('description', models.CharField(default='', max_length=300)),
                ('document', models.FileField(upload_to='reports/')),
            ],
        ),
    ]
