# Generated by Django 3.0.6 on 2020-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shameem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
