# Generated by Django 3.0.6 on 2020-05-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shameem', '0003_language_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language_skill',
        ),
    ]
