# Generated by Django 3.0.6 on 2020-05-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shameem', '0005_language_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
