# Generated by Django 3.0.6 on 2020-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shameem', '0006_auto_20200523_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('course', models.CharField(default='', max_length=100)),
                ('institution', models.CharField(default='', max_length=300)),
                ('academic_year', models.CharField(default='', max_length=20)),
                ('website', models.CharField(default='', max_length=100)),
                ('institution_image', models.ImageField(upload_to='dp/')),
                ('university_logo', models.ImageField(upload_to='dp/')),
            ],
        ),
    ]
