# Generated by Django 3.0.6 on 2020-05-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shameem', '0007_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='university_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='education',
            name='university_website',
            field=models.CharField(default='', max_length=300),
        ),
    ]
