# Generated by Django 3.0.6 on 2020-05-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shameem', '0008_auto_20200523_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('hobby', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(upload_to='dp/')),
            ],
        ),
    ]
